### ISSUE TITLE
[ recommend ] why ..... 有點弱，可以加強

### ISSUE THREAD

**Issue by troie** [sayidly/idoogu#4]
<img width="230" alt="螢幕快照 2019-12-25 下午5 25 39" src="https://user-images.githubusercontent.com/101321/71441361-23c73400-273c-11ea-8422-a338fb83d2fa.png">
 why ..... 有點弱，可以加強

**Comment by sayidly** [comment]
需要更多的信息，关于这个，是否删掉 Why idoogu 这些小标呢？

**Comment by troie** [comment]
可以啊，我以為是你加上去的，哈哈
