### ISSUE TITLE
[ recommend ] 擠擠吧，試著把它們擠成一行

### ISSUE THREAD

**Issue by troie** [sayidly/idoogu#7]
<img width="397" alt="螢幕快照 2019-12-25 下午5 56 01" src="https://user-images.githubusercontent.com/101321/71442229-ff6d5680-273f-11ea-932c-8b86e46012f7.png">

**Comment by sayidly** [comment]
5个一行太挤了，改成了3个一行，分两行。

**Comment by troie** [comment]
ok, 掉一個下來很怪，兩個就好點
