### ISSUE TITLE
[ recommend ] 這個上線前得先處理，wechat search

### ISSUE THREAD

**Issue by troie** [sayidly/idoogu#9]
![wechat-search-dark](https://user-images.githubusercontent.com/101321/71481548-42f7bb80-2839-11ea-818c-186d9e172097.png)
![wechat-search-white](https://user-images.githubusercontent.com/101321/71481549-43905200-2839-11ea-9f25-77ca98562c98.png)

**Comment by sayidly** [comment]
对，差点忘了。
只针对手机版加对吗？

**Comment by troie** [comment]
應該都需要吧，忘了，把就是哎嘟咕 p 掉吧，只需要搜尋 idoogu 就可以了

**Comment by sayidly** [comment]
加在 footer 吗，你们觉得呢

@troie @uniweep
